**Dataset info**

This dataset was taken from Centers for Disease Control and Prevention (CDC): Pregnancy-Related Deaths: Data From Maternal Mortality Review Committees in 38 U.S. States, 2020. Link: https://www.cdc.gov/maternal-mortality/php/data-research/index.html

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('maternal_mortality.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Condition                           22 non-null     object
 1   Number of pregnancy-related deaths  22 non-null     int64
 2   %                                   22 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 660.0+ bytes

In [3]:
df.describe()

       Number of pregnancy-related deaths          %
count                           22.000000  22.000000
mean                            29.545455   5.795455
std                             32.595248   6.366092
min                              2.000000   0.400000
25%                              4.250000   0.850000
50%                             10.500000   2.100000
75%                             48.500000   9.500000
max                            115.000000  22.500000

In [4]:
df.sort_values(by='Condition', ascending=False).head(5)

,Condition,Number of pregnancy-related deaths,%
21,Renal diseases,2,0.4
14,Pulmonary conditions,7,1.4
3,Other cardiovascular conditions,50,9.8
18,Neurologic/neurovascular conditions,4,0.8
13,Metabolic/endocrine,9,1.8
0,Mental health conditions,115,22.5
10,Injury,11,2.2
4,Infection,84,16.4
8,Hypertensive disorders of pregnancy,36,7.1
6,Hemorrhage,57,11.2